### ISSUE TITLE
Feature: Main Screen

### ISSUE THREAD

**Issue by Zeronfinity** [Zeronfinity/CPfy#3]
## Epic Title

Feature: Main Screen

### Epic Description

This feature will add the initial screen that is shown when app is launched.
The screen should a list of upcoming contests  (within a certain interval e.g. next 7 days, sorted according to begin time in ascending order).

### List of Tasks (Completion in order recommended)

- [x] [Task 1: Fetch contest data through CLIST API](https://github.com/Zeronfinity/CPfy/issues/5)
- [x] [Task 2: Show upcoming contests in main screen](https://github.com/Zeronfinity/CPfy/issues/7)
- [x] [Task 3: Fetch images given as links in JSON](https://github.com/Zeronfinity/CPfy/issues/9)
- [ ] [Task 4: Optimize contest JSON fetching and parsing](https://github.com/Zeronfinity/CPfy/issues/17)
- [x] [Task 5: Add user option to filter contests by parameters](https://github.com/Zeronfinity/CPfy/issues/15)
- [x] [Task 6: Add contest page open feature upon clicking launch icon](https://github.com/Zeronfinity/CPfy/issues/16)

### Implemented UI Screenshots

<img alt="Screenshot_1595613435" src="https://user-images.githubusercontent.com/34229687/88452304-60e4d780-ce7f-11ea-89b6-e683330caace.png" width = 400> <img src="https://user-images.githubusercontent.com/34229687/88452302-5f1b1400-ce7f-11ea-886e-f7643de93908.png" alt="Screenshot_1595606149" width = 400>
